name: Deploy Chat App to Google Cloud

on:
  push:
    branches:
      - master  # Change from 'main' to 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH for GCP VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts

      - name: Clean old app on VM
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} "rm -rf ~/chat-app && mkdir ~/chat-app"

      - name: Copy code to VM
        run: |
          scp -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new ./* ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }}:~/chat-app

      - name: Run Docker Compose on VM
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd ~/chat-app
            # Set environment variables for database connection and OAuth2
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            
            # Clean up any existing containers and volumes
            docker-compose down -v
            
            # Run docker-compose with environment variables
            docker-compose -f docker-compose.yml up -d
          EOF

      - name: Remove Frontend and Backend Docker Images
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd ~/chat-app
            # Remove frontend and backend Docker images while keeping the containers running
            docker image rm -f chat-app_frontend chat-app_backend
          EOF
